# Generated by Django 4.2.7 on 2023-11-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_alter_photo_options_photo_timestamp_photo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='url',
            field=models.URLField(default=2),
            preserve_default=False,
        ),
    ]
